controller_list:
  - name: pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - mir2/ur5_shoulder_pan_joint
      - mir2/ur5_shoulder_lift_joint
      - mir2/ur5_elbow_joint
      - mir2/ur5_wrist_1_joint
      - mir2/ur5_wrist_2_joint
      - mir2/ur5_wrist_3_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - mir2/ur5_robotiq_85_left_knuckle_joint